version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: neiu-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 693753_CS315_ggh
      MYSQL_DATABASE: ggheata
      MYSQL_USER: ggheata
      MYSQL_PASSWORD: 693753_CS315_ggh
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
volumes:
  mysql_data: